if(EXISTS "/home/cinwa/cppzmq-4.9.0/build/tests/unit_tests_tests-b12d07c.cmake")
  include("/home/cinwa/cppzmq-4.9.0/build/tests/unit_tests_tests-b12d07c.cmake")
else()
  add_test(unit_tests_NOT_BUILT-b12d07c unit_tests_NOT_BUILT-b12d07c)
endif()
