add_test( [==[buffer default ctor]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[buffer default ctor]==]  )
set_tests_properties( [==[buffer default ctor]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[buffer data ctor]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[buffer data ctor]==]  )
set_tests_properties( [==[buffer data ctor]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[const_buffer operator+]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[const_buffer operator+]==]  )
set_tests_properties( [==[const_buffer operator+]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[mutable_buffer operator+]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[mutable_buffer operator+]==]  )
set_tests_properties( [==[mutable_buffer operator+]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[mutable_buffer creation basic]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[mutable_buffer creation basic]==]  )
set_tests_properties( [==[mutable_buffer creation basic]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[const_buffer creation basic]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[const_buffer creation basic]==]  )
set_tests_properties( [==[const_buffer creation basic]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[mutable_buffer creation C array]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[mutable_buffer creation C array]==]  )
set_tests_properties( [==[mutable_buffer creation C array]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[const_buffer creation C array]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[const_buffer creation C array]==]  )
set_tests_properties( [==[const_buffer creation C array]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[mutable_buffer creation array]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[mutable_buffer creation array]==]  )
set_tests_properties( [==[mutable_buffer creation array]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[const_buffer creation array]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[const_buffer creation array]==]  )
set_tests_properties( [==[const_buffer creation array]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[const_buffer creation array 2]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[const_buffer creation array 2]==]  )
set_tests_properties( [==[const_buffer creation array 2]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[mutable_buffer creation vector]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[mutable_buffer creation vector]==]  )
set_tests_properties( [==[mutable_buffer creation vector]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[const_buffer creation vector]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[const_buffer creation vector]==]  )
set_tests_properties( [==[const_buffer creation vector]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[const_buffer creation string]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[const_buffer creation string]==]  )
set_tests_properties( [==[const_buffer creation string]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[mutable_buffer creation string]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[mutable_buffer creation string]==]  )
set_tests_properties( [==[mutable_buffer creation string]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[const_buffer creation with str_buffer]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[const_buffer creation with str_buffer]==]  )
set_tests_properties( [==[const_buffer creation with str_buffer]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[const_buffer creation with zbuf string literal char]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[const_buffer creation with zbuf string literal char]==]  )
set_tests_properties( [==[const_buffer creation with zbuf string literal char]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[const_buffer creation with zbuf string literal wchar_t]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[const_buffer creation with zbuf string literal wchar_t]==]  )
set_tests_properties( [==[const_buffer creation with zbuf string literal wchar_t]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[const_buffer creation with zbuf string literal char16_t]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[const_buffer creation with zbuf string literal char16_t]==]  )
set_tests_properties( [==[const_buffer creation with zbuf string literal char16_t]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[const_buffer creation with zbuf string literal char32_t]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[const_buffer creation with zbuf string literal char32_t]==]  )
set_tests_properties( [==[const_buffer creation with zbuf string literal char32_t]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[buffer of structs]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[buffer of structs]==]  )
set_tests_properties( [==[buffer of structs]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message default constructed]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message default constructed]==]  )
set_tests_properties( [==[message default constructed]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message swap]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message swap]==]  )
set_tests_properties( [==[message swap]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message constructor with iterators]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message constructor with iterators]==]  )
set_tests_properties( [==[message constructor with iterators]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message constructor with size]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message constructor with size]==]  )
set_tests_properties( [==[message constructor with size]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message constructor with buffer and size]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message constructor with buffer and size]==]  )
set_tests_properties( [==[message constructor with buffer and size]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message constructor with char array]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message constructor with char array]==]  )
set_tests_properties( [==[message constructor with char array]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message constructor with container - deprecated]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message constructor with container - deprecated]==]  )
set_tests_properties( [==[message constructor with container - deprecated]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message constructor with container of trivial data]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message constructor with container of trivial data]==]  )
set_tests_properties( [==[message constructor with container of trivial data]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message constructor with strings]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message constructor with strings]==]  )
set_tests_properties( [==[message constructor with strings]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message move constructor]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message move constructor]==]  )
set_tests_properties( [==[message move constructor]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message assign move empty before]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message assign move empty before]==]  )
set_tests_properties( [==[message assign move empty before]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message assign move empty after]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message assign move empty after]==]  )
set_tests_properties( [==[message assign move empty after]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message assign move empty before and after]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message assign move empty before and after]==]  )
set_tests_properties( [==[message assign move empty before and after]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message equality self]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message equality self]==]  )
set_tests_properties( [==[message equality self]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message equality equal]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message equality equal]==]  )
set_tests_properties( [==[message equality equal]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message equality equal empty]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message equality equal empty]==]  )
set_tests_properties( [==[message equality equal empty]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message equality non equal]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message equality non equal]==]  )
set_tests_properties( [==[message equality non equal]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message equality non equal rhs empty]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message equality non equal rhs empty]==]  )
set_tests_properties( [==[message equality non equal rhs empty]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message equality non equal lhs empty]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message equality non equal lhs empty]==]  )
set_tests_properties( [==[message equality non equal lhs empty]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message to string]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message to string]==]  )
set_tests_properties( [==[message to string]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message is not shared]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message is not shared]==]  )
set_tests_properties( [==[message is not shared]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message is shared]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message is shared]==]  )
set_tests_properties( [==[message is shared]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[message move is not shared]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[message move is not shared]==]  )
set_tests_properties( [==[message move is not shared]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[context construct default and destroy]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[context construct default and destroy]==]  )
set_tests_properties( [==[context construct default and destroy]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[context create, close and destroy]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[context create\, close and destroy]==]  )
set_tests_properties( [==[context create, close and destroy]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[context shutdown]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[context shutdown]==]  )
set_tests_properties( [==[context shutdown]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[context shutdown again]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[context shutdown again]==]  )
set_tests_properties( [==[context shutdown again]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[context swap]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[context swap]==]  )
set_tests_properties( [==[context swap]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[context - use socket after shutdown]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[context - use socket after shutdown]==]  )
set_tests_properties( [==[context - use socket after shutdown]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[context set/get options]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[context set/get options]==]  )
set_tests_properties( [==[context set/get options]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket default ctor]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket default ctor]==]  )
set_tests_properties( [==[socket default ctor]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket create destroy]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket create destroy]==]  )
set_tests_properties( [==[socket create destroy]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket create assign]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket create assign]==]  )
set_tests_properties( [==[socket create assign]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket create by enum and destroy]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket create by enum and destroy]==]  )
set_tests_properties( [==[socket create by enum and destroy]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket swap]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket swap]==]  )
set_tests_properties( [==[socket swap]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket options]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket options]==]  )
set_tests_properties( [==[socket options]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket check array options]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket check array options]==]  )
set_tests_properties( [==[socket check array options]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket check integral options]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket check integral options]==]  )
set_tests_properties( [==[socket check integral options]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket flags]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket flags]==]  )
set_tests_properties( [==[socket flags]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket readme example]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket readme example]==]  )
set_tests_properties( [==[socket readme example]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket sends and receives const buffer]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket sends and receives const buffer]==]  )
set_tests_properties( [==[socket sends and receives const buffer]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket send none sndmore]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket send none sndmore]==]  )
set_tests_properties( [==[socket send none sndmore]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket send dontwait]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket send dontwait]==]  )
set_tests_properties( [==[socket send dontwait]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket send exception]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket send exception]==]  )
set_tests_properties( [==[socket send exception]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket recv none]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket recv none]==]  )
set_tests_properties( [==[socket recv none]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket send recv message_t]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket send recv message_t]==]  )
set_tests_properties( [==[socket send recv message_t]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket send recv message_t by pointer]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket send recv message_t by pointer]==]  )
set_tests_properties( [==[socket send recv message_t by pointer]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket recv dontwait]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket recv dontwait]==]  )
set_tests_properties( [==[socket recv dontwait]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket recv exception]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket recv exception]==]  )
set_tests_properties( [==[socket recv exception]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket proxy]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket proxy]==]  )
set_tests_properties( [==[socket proxy]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket proxy steerable]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket proxy steerable]==]  )
set_tests_properties( [==[socket proxy steerable]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket_ref default init]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket_ref default init]==]  )
set_tests_properties( [==[socket_ref default init]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket_ref create from nullptr]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket_ref create from nullptr]==]  )
set_tests_properties( [==[socket_ref create from nullptr]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket_ref create from handle]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket_ref create from handle]==]  )
set_tests_properties( [==[socket_ref create from handle]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket_ref compare]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket_ref compare]==]  )
set_tests_properties( [==[socket_ref compare]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket_ref compare from socket_t]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket_ref compare from socket_t]==]  )
set_tests_properties( [==[socket_ref compare from socket_t]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket_ref assignment]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket_ref assignment]==]  )
set_tests_properties( [==[socket_ref assignment]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket_ref swap]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket_ref swap]==]  )
set_tests_properties( [==[socket_ref swap]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[socket_ref type punning]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[socket_ref type punning]==]  )
set_tests_properties( [==[socket_ref type punning]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[multipart legacy test]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[multipart legacy test]==]  )
set_tests_properties( [==[multipart legacy test]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[recv_multipart test]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[recv_multipart test]==]  )
set_tests_properties( [==[recv_multipart test]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[recv_multipart_n test]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[recv_multipart_n test]==]  )
set_tests_properties( [==[recv_multipart_n test]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[send_multipart test]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[send_multipart test]==]  )
set_tests_properties( [==[send_multipart test]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[multipart codec empty]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[multipart codec empty]==]  )
set_tests_properties( [==[multipart codec empty]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[multipart codec small]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[multipart codec small]==]  )
set_tests_properties( [==[multipart codec small]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[multipart codec big]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[multipart codec big]==]  )
set_tests_properties( [==[multipart codec big]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[multipart codec decode bad data overflow]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[multipart codec decode bad data overflow]==]  )
set_tests_properties( [==[multipart codec decode bad data overflow]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[multipart codec decode bad data extra data]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[multipart codec decode bad data extra data]==]  )
set_tests_properties( [==[multipart codec decode bad data extra data]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[multipart codec free function with vector of message_t]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[multipart codec free function with vector of message_t]==]  )
set_tests_properties( [==[multipart codec free function with vector of message_t]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[multipart codec free function with vector of const_buffer]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[multipart codec free function with vector of const_buffer]==]  )
set_tests_properties( [==[multipart codec free function with vector of const_buffer]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[multipart codec free function with vector of mutable_buffer]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[multipart codec free function with vector of mutable_buffer]==]  )
set_tests_properties( [==[multipart codec free function with vector of mutable_buffer]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[multipart codec free function with multipart_t]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[multipart codec free function with multipart_t]==]  )
set_tests_properties( [==[multipart codec free function with multipart_t]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[multipart codec static method decode to multipart_t]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[multipart codec static method decode to multipart_t]==]  )
set_tests_properties( [==[multipart codec static method decode to multipart_t]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[monitor create destroy]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[monitor create destroy]==]  )
set_tests_properties( [==[monitor create destroy]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[monitor move construct]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[monitor move construct]==]  )
set_tests_properties( [==[monitor move construct]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[monitor move assign]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[monitor move assign]==]  )
set_tests_properties( [==[monitor move assign]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[monitor init event count]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[monitor init event count]==]  )
set_tests_properties( [==[monitor init event count]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[monitor init abort]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[monitor init abort]==]  )
set_tests_properties( [==[monitor init abort]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[monitor from move assigned socket]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[monitor from move assigned socket]==]  )
set_tests_properties( [==[monitor from move assigned socket]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
add_test( [==[range SFINAE]==] /home/cinwa/cppzmq-4.9.0/build/tests/unit_tests [==[range SFINAE]==]  )
set_tests_properties( [==[range SFINAE]==] PROPERTIES WORKING_DIRECTORY /home/cinwa/cppzmq-4.9.0/build/tests)
set( unit_tests_TESTS [==[buffer default ctor]==] [==[buffer data ctor]==] [==[const_buffer operator+]==] [==[mutable_buffer operator+]==] [==[mutable_buffer creation basic]==] [==[const_buffer creation basic]==] [==[mutable_buffer creation C array]==] [==[const_buffer creation C array]==] [==[mutable_buffer creation array]==] [==[const_buffer creation array]==] [==[const_buffer creation array 2]==] [==[mutable_buffer creation vector]==] [==[const_buffer creation vector]==] [==[const_buffer creation string]==] [==[mutable_buffer creation string]==] [==[const_buffer creation with str_buffer]==] [==[const_buffer creation with zbuf string literal char]==] [==[const_buffer creation with zbuf string literal wchar_t]==] [==[const_buffer creation with zbuf string literal char16_t]==] [==[const_buffer creation with zbuf string literal char32_t]==] [==[buffer of structs]==] [==[message default constructed]==] [==[message swap]==] [==[message constructor with iterators]==] [==[message constructor with size]==] [==[message constructor with buffer and size]==] [==[message constructor with char array]==] [==[message constructor with container - deprecated]==] [==[message constructor with container of trivial data]==] [==[message constructor with strings]==] [==[message move constructor]==] [==[message assign move empty before]==] [==[message assign move empty after]==] [==[message assign move empty before and after]==] [==[message equality self]==] [==[message equality equal]==] [==[message equality equal empty]==] [==[message equality non equal]==] [==[message equality non equal rhs empty]==] [==[message equality non equal lhs empty]==] [==[message to string]==] [==[message is not shared]==] [==[message is shared]==] [==[message move is not shared]==] [==[context construct default and destroy]==] [==[context create, close and destroy]==] [==[context shutdown]==] [==[context shutdown again]==] [==[context swap]==] [==[context - use socket after shutdown]==] [==[context set/get options]==] [==[socket default ctor]==] [==[socket create destroy]==] [==[socket create assign]==] [==[socket create by enum and destroy]==] [==[socket swap]==] [==[socket options]==] [==[socket check array options]==] [==[socket check integral options]==] [==[socket flags]==] [==[socket readme example]==] [==[socket sends and receives const buffer]==] [==[socket send none sndmore]==] [==[socket send dontwait]==] [==[socket send exception]==] [==[socket recv none]==] [==[socket send recv message_t]==] [==[socket send recv message_t by pointer]==] [==[socket recv dontwait]==] [==[socket recv exception]==] [==[socket proxy]==] [==[socket proxy steerable]==] [==[socket_ref default init]==] [==[socket_ref create from nullptr]==] [==[socket_ref create from handle]==] [==[socket_ref compare]==] [==[socket_ref compare from socket_t]==] [==[socket_ref assignment]==] [==[socket_ref swap]==] [==[socket_ref type punning]==] [==[multipart legacy test]==] [==[recv_multipart test]==] [==[recv_multipart_n test]==] [==[send_multipart test]==] [==[multipart codec empty]==] [==[multipart codec small]==] [==[multipart codec big]==] [==[multipart codec decode bad data overflow]==] [==[multipart codec decode bad data extra data]==] [==[multipart codec free function with vector of message_t]==] [==[multipart codec free function with vector of const_buffer]==] [==[multipart codec free function with vector of mutable_buffer]==] [==[multipart codec free function with multipart_t]==] [==[multipart codec static method decode to multipart_t]==] [==[monitor create destroy]==] [==[monitor move construct]==] [==[monitor move assign]==] [==[monitor init event count]==] [==[monitor init abort]==] [==[monitor from move assigned socket]==] [==[range SFINAE]==])
